### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by v-ko** [openscoring/openscoring-python#10]
I'm receiving an error when I try to run the example code: 

> from openscoring import Openscoring
> os = Openscoring("http://localhost:8080/openscoring")
> kwargs = {"auth" : ("admin", "adminadmin")}
> os.deployFile("Iris", "model.pmml", **kwargs)

But I get the following error:

> Traceback (most recent call last):
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
>     raise err
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/usr/lib/python3.7/http/client.py", line 1229, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.7/http/client.py", line 956, in send
>     self.connect()
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
>     conn = self._new_conn()
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
>     self, "Failed to establish a new connection: %s" % e)
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f84c98f3668>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /openscoring/model/Iris (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84c98f3668>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/user/builds/weather/test.py", line 4, in <module>
>     os.deployFile("Iris", "model.pmml", **kwargs)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/openscoring/__init__.py", line 118, in deployFile
>     return self.deploy(id, instream, **kwargs)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/openscoring/__init__.py", line 112, in deploy
>     response = self._check_response(requests.put(self._model_url(id), **kwargs))
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/requests/api.py", line 131, in put
>     return request('put', url, data=data, **kwargs)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/user/builds/weather/venv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /openscoring/model/Iris (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f84c98f3668>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> Process finished with exit code 1

**Comment by vruusmann** [comment]
> os = Openscoring("http://localhost:8080/openscoring")
> Failed to establish a new connection: [Errno 111] Connection refused

Do you have an Openscoring REST web service running in your local computer, at port 8080?

You can't connect to a service that hasn't been started.

**Comment by v-ko** [comment]
Thanks for the reply, donno why I'd never used Openscoring before and thought the server got started with the Openscoring constructor.

**Comment by xalekx** [comment]
Having the same error
ConnectionError: HTTPConnectionPool(host='localhost', port=8090): Max retries exceeded with url: /openscoring/model/TEST12321 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6b9ee1d978>: Failed to establish a new connection: [Errno 111] Connection refused'))

I am using 1.4.5 openscoring on Linux. 
Whenever i try to deploy a model with curl the connection works. But evenever i try deploying a model via Openscoring ( python library version 0.4.3) the error above shows.

The server is up and running and i can download or evaluate models but using the python deploy function doesnt work.

Is there any way to fix this?

**Comment by vruusmann** [comment]
> Is there any way to fix this?

Double-check your configuration. Specifically, I would advise you to check port numbers, as Openscoring-Service typically listens on port 8080, but you're attempting to connect to port 8090.

**Comment by xalekx** [comment]
My rabbitmq runs on 8080 thats why i am binding it to 8090. I will try  to re map rabbitmq to different port and use 8080 for OpenScoring

**Comment by xalekx** [comment]
Tried with 8080 yetagain.
`curl -X PUT --data-binary @/home/TEST2.pmml -H "Content-type: text/xml" http://localhost:8080/openscoring/model/Test2`

works just fine

but the code in python 
```
from openscoring import Openscoring
os = Openscoring("http://localhost:8080/openscoring")

kwargs = {"auth" : ("admin", "adminadmin")}

os.deployFile("Test3", "TEST3.pmml", **kwargs)

```
doesnt work
