### ISSUE TITLE
No JSON Object could be decoded

### ISSUE THREAD

**Issue by mohammedayub44** [openscoring/openscoring-python#2]
I'm running this project in Python 2.7 and it gives me this error while uploading to the PMML model.

 os.deploy("Iris", "C:\Users\moham\Documents\GitHub\openscoring-python\DecisionTreeIris.pmml", **kwargs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\moham\AppData\Roaming\Python\Python27\site-packages\openscoring\__init__.py", line 84, in deploy
    modelResponse = ModelResponse(**json.loads(response.text))
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
**ValueError: No JSON object could be decoded**

**Comment by mohammedayub44** [comment]
I'm trying to do this on windows  and have configured IIS localhost:80, but it gives me an 404 error on /model/{ID} url. I'm a missing to setup something so I can create correct/working endpoints ?

**Comment by vruusmann** [comment]
This is a Python client package for the [Openscoring REST web service](https://github.com/openscoring/openscoring). It is not designed for interacting with arbitrary IIS services.

**Comment by mohammedayub44** [comment]
Sorry my bad. Just realized that.
