### ISSUE TITLE
Batch csv evaluation returns NULL id's

### ISSUE THREAD

**Issue by saffrydaffry** [openscoring/openscoring-python#3]
I sent the /csv endpoint a features.csv file with "id" in the header. According to the documentation, this should result in the id's being reprinted in the response (and output csv). However, I'm still seeing id=Null in the response and no id column in the resulting csv.

My input file looks something like

```
"id","date","feat1","feat2",...,"featn"
"23029854","2017-01-01","2.0","1.0",..."5.0"
```

My code is something like:

```
os = openscoring.Openscoring("http://{host}:8080/openscoring".format(host=HOSTS[args.host]))
os.deploy(model_name, model_pmml, **openscoring_login)
os.evaluateCsv(model_name, input_csv, output_csv)
```

Then the output file:
```
true_label,probability_0,probability_1
0,0.9991488452182992,8.511547817011017E-4
0,0.9779992879224841,0.022000712077515847
0,0.9779992879224841,0.022000712077515847
```

And the EvaluationResponse:
```
INFO: Returned EvaluationResponse{id=null, result={true_label=0, probability_0=0.9349664396728562, probability_1=0.0650335603271438}}
```

I tried modifying the "id" column even though the docs say reading "id" is case-insensitive", and removing the double quotes. Is there something else I might be doing wrong?

Thanks

**Comment by vruusmann** [comment]
The value of the `EvaluationResponse@id` attribute is the same as the `EvaluationRequest@id` attribute. Does your evaluation request JSON object have a non-null Id?

I just tested relevant Openscoring REST API endpoints using the `curl` command-line application (copy-pasted examples from the README file) and everything works just fine. Have you tested your CSV file with the `curl` command-line application already?

What is your "requests" Python package version?

**Comment by saffrydaffry** [comment]
I haven't tried cURL yet, once I try sending a request to /csv I'll post the results.  My requests library version is 2.18.4.

Thanks

**Comment by saffrydaffry** [comment]
I just tested using cURL and the /csv with
```
curl -X POST --data-binary @features.csv -H "Content-type: text/plain; charset=UTF-8" http://localhost:8080/openscoring/model/testmodel/csv > curl_output.csv
```
and it looks like from cURL the ID's are processed correctly:

```
head curl_output.csv
id,true_label,probability_0,probability_1
57977,0,0.9991488452182992,8.511547817011017E-4
31721,0,0.9779992879224841,0.022000712077515847
55943,0,0.9779992879224841,0.022000712077515847
35826,0,0.9929877781321543,0.00701222186784629
```
This is using the same file as previously. I'm not sure why curl and python would give different results?

**Comment by vruusmann** [comment]
I have added a unit test to demonstrate that everything works as advertised:
https://github.com/openscoring/openscoring-python/blob/master/openscoring/tests/__init__.py#L12-L51

In my computer, this test passes cleanly with Python 2.7 (+requests 2.10) and Python 3.4 (+requests 2.18):
```
$ cd openscoring-python
$ nosetests-2.7
$ nosetests-3.4
```

The output on both cases is this:
```
Ran 7 tests in 0.281s

OK
```

Also, there's a new method `Openscoring.evaluateDataFrame(id, df)`, which deals with in-memory Pandas' `DataFrame` objects (as opposed to CSV files). Their formatting and parsing uses fixed delimiter and quote chars, and therefore should be less error prone.

Anyway, my resolution is that the Openscoring-Python client library is correct, and the problem is located somewhere in your computer.

**Comment by saffrydaffry** [comment]
I will continue to look at my setup, it does seem like it's something in my system. Thanks for adding the evaluateDataFrame method. I look forward to trying it out.

Thanks for all your help!
