### ISSUE TITLE
How to get prediction probabilities?

### ISSUE THREAD

**Issue by Tenceto** [openscoring/openscoring-python#9]
Suppose we have any PMML classifier and we evaluate it using this library. Then, the output for each observation is the class the model predicts they belong to. However, I'd like to know the probability of each observation to belong to each class as well.

Is there a way to achieve this?

**Comment by vruusmann** [comment]
> However, I'd like to know the probability of each observation to belong to each class as well.

Openscoring/JPMML-Evaluator gives all aspects of a prediction - the predicted class label, and the associated probability distribution - in one go (ie. there are no separate `predict(X)` and `predict_proba(X)` endpoints).

Please see the README.md file out the main Openscoring REST web service project.

First, you can distinguish between the primary prediction (aka target) and secondary prediction (aka output) fields based on the model schema information:
https://github.com/openscoring/openscoring#get-modelid

In the "DecisionTreeIris" example, there is a sole target field ("Species"), and four output fields ("Probability_setosa", "Probability_versicolor", "Probability_virginica" and "Node_Id"). As the name suggests, the probability distribution is represented using the first three output fields.
